name: sass
version: 0.0.4+2
description: >
  Sass-transformer for pub-serve and pub-build.
author: Juha Komulainen <juha.komulainen@evident.fi>
homepage: https://bitbucket.org/evidentsolutions/dart-sass
dependencies:
  barback: ">=0.9.0 <0.12.0"
  utf: ">=0.9.0 <0.9.1"
dev_dependencies:
  unittest: ">=0.9.0 <0.9.4"
