name: sass
version: 0.1.0
description: >
  Sass-transformer for pub-serve and pub-build.
author: Juha Komulainen <juha.komulainen@evident.fi>
homepage: https://bitbucket.org/evidentsolutions/dart-sass
dependencies:
  barback: ">=0.9.0 <0.14.0"
  utf: ">=0.9.0 <0.9.1"
dev_dependencies:
  unittest: ">=0.9.0 <0.11.0"
