name: dart_sass_angular2
version: 0.0.1
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  angular2: any
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  dart_sass_transformer: any
transformers:
- dart_sass_transformer
- angular2:
    entry_points: web/main.dart
- dart_to_js_script_rewriter
